-- AlterTable
ALTER TABLE "Passes" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "number" DROP NOT NULL,
ALTER COLUMN "expiry" DROP NOT NULL,
ALTER COLUMN "cvc" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "url" DROP NOT NULL,
ALTER COLUMN "username" DROP NOT NULL,
ALTER COLUMN "content" DROP NOT NULL,
ALTER COLUMN "network" DROP NOT NULL,
ALTER COLUMN "cardType" DROP NOT NULL;
